---
- hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
    - name: update all hosts 
      apt:
        update_cache: yes
        
- hosts: webservers 
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: update all webservers 
      apt:
        update_cache: true

    - name: install nginx
      apt:
        name: nginx
        state: latest


    - name: pip3 install
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Installing flask 
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: gunicorn installation 
      apt:
        name: gunicorn

    - name: copy flask app code  
      copy:
        src: app.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        mode: '0644'

    - name: deploying Flask application 
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 app:app

    - name: install snmpd in webservers
      apt:
        name: snmpd
        state: latest

    - name: configure snmpd for monitoring
      template:
             src: snmpd.conf
             dest: /etc/snmp/snmpd.conf

    - name: restarting snmpd
      service:
            name: snmpd
            state: restarted

- hosts: all
  gather_facts: true
#Now Installing haproxy, configuring it and then haproxy restart
- hosts: HAproxy # gathering haproxy host
  become: true
  tasks:
    - name: update HAproxy
      apt:
        update_cache: yes

    - name: Installing HAPROXY
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy to loadbalance flask app
      template:
             src: haproxy.cfg.j2
             dest: /etc/haproxy/haproxy.cfg

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: Installing Nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest

    - name: configure nginx udp port
      template:
             src: nginxport.conf
             dest: /etc/nginx/sites-available/default

    - name: configure udp for loadbalancing snmp
      template:
             src: nginxload.conf
             dest: /etc/nginx/nginx.conf

    - name: Restart Nginx
      service:
            name: nginx
            state: restarted
