---
- hosts: all
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
        - name: "Update Cache"
          apt:
              update_cache: yes


- name: Configure Backend Web Servers
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Installing Flask
      pip:
         executable: pip3
         name: flask
         state: latest

    - name: Serve Flask App - pre-fork worker model
      apt:
        name: gunicorn

    - name: Copy Python file to app.py
      copy:
         src: /$PWD/app.py
         dest: /home/ubuntu/app.py
         owner: ubuntu
         mode: '0644'

    - name: Run Flask app
      shell: gunicorn -w 2 -D -b 0.0.0.0:8000 app1:app
    
    - name: installing snmpd in webservers
      apt:
        name: snmpd
        state: latest
        update_cache: true

    - name: restart snmpd
      service: 
            name: snmpd
            state: restarted

- hosts: HAproxy
  become: yes
  tasks:
          - name: Update cache
            apt:
                   update_cache: yes

          - name: "Installing haproxy"
            package:
                    name: haproxy
                    state: present


          - name: "Copying configuration file"
            template:
                    src: /$PWD/haproxy.cfg.j2
                    dest: /etc/haproxy/haproxy.cfg


          - name: "restarting haproxy services"
            service:
                    name: "haproxy"
                    state: restarted

          - name: Install Nginx
            apt:
              name: nginx
              update_cache: yes
              state: latest

          - name: configure nginx port
            template:
                      src: /$PWD/nginxport.conf
                      dest: /etc/nginx/sites-available/default

          - name: configure udp for loadbalancing snmp
            template:
                      src: /$PWD/nginxload.conf
                      dest: /etc/nginx/nginx.conf

          - name: Restart Nginx
            service:
                    name: "nginx"
                    state: restarted
